accounts/urls.py
from django.urls import path

from .views import user_profile_view, SignupView

app_name = 'accounts'
urlpatterns = [
    path('profile/', user_profile_view, name='profile'),
    path('signup/', SignupView.as_view(), name='signup')
]

api/users/urls.py
from django.urls import path

from .views import UserListAPIView, UserDetailAPIView, RegisterUserView, OTPVerifyUser

app_name = 'api-user'

urlpatterns = [
    path('registration/', RegisterUserView.as_view(), name='signup'),
    path('', UserListAPIView.as_view(), name='list'),
    path('<int:pk>/', UserDetailAPIView.as_view(), name='detail'),
    path('verify/', OTPVerifyUser.as_view(), name='verify-user')
]

blog/urls.py
from django.urls import path

from .views import PostListView, PostDetailView, CreatePostView, DeletePostView, UpdatePostView


app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='list'),
    path('<int:pk>/<str:slug>/', PostDetailView.as_view(), name='detail'),
    path('add/', CreatePostView.as_view(), name='add'),
    path('<int:pk>/<str:slug>/delete/', DeletePostView.as_view(), name='delete'),
    path('<int:pk>/<str:slug>/edit/', UpdatePostView.as_view(), name='edit'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import permissions 
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title='Blog API',
        default_version='v1',
        description="A sample API for learning DRF",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="hello@example.com"),
        license=openapi.License(name="BSD License"),
        ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    
    # API VERSION 1
    path('api/v1/blog/', include('api.blog.urls')),
    path('api/v1/users/', include('api.users.urls')),
    
    # AUTHENTICATION
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # Documenting
    path('swagger/', schema_view.with_ui(
        'swagger', cache_timeout=0
    ), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui(
        'redoc', cache_timeout=0
    ), name='schema-redoc'),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, AbstractUser
from django.utils import timezone

from .validators import PhoneNumberValidator
from .messages import UserMessage

from .managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    phone_number = models.CharField(
        max_length=14,
        unique=True,
        help_text=UserMessage.PHONE_NUMBER_HELP_TEXT.value,
        validators=[PhoneNumberValidator],
    )
    username = models.CharField(max_length=200, unique=True)
    first_name = models.CharField(max_length=200, blank=True, default='')
    last_name = models.CharField(max_length=200, blank=True, default='')
    email = models.EmailField(default='', blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_verified = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['username',]

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    objects = CustomUserManager()

    def __str__(self):
        return self.phone_number

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('phone_number', 'username', 'email',)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('phone_number', 'email', 'username',) 


class UserProfileForm(forms.ModelForm):
     class Meta:
        model = CustomUser
        fields = ('phone_number', 'email', 'username', 'first_name', 'last_name') 

accounts/views.py
from audioop import reverse
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.generic import CreateView

from accounts.models import CustomUser

from .messages import UserMessage
from api.users.messages import ViewMessages
from .forms import UserProfileForm, CustomUserCreationForm


@login_required
def user_profile_view(request: HttpRequest) -> HttpResponse:
    form = UserProfileForm(instance=request.user)

    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            text = UserMessage.PROFILE_UPDATED_SUCCESSFULLY.value
            messages.add_message(request, messages.SUCCESS, text)
            return redirect(request.path_info)
        else:
            text = ViewMessages.SOMETHING_WENT_WRONG.value
            messages.add_message(request, messages.WARNING, text)
            form = UserProfileForm(instance=request.user, data=request.POST)

    context = {
        'form': form
    }
    return render(request, 'accounts/profile.html', context)


class SignupView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'registration/signup.html'
    
    def get_success_url(self) -> str:
        return reverse('login')

accounts/templates/accounts/author_not_user.html
{% extends 'blog/base.html' %}{% block title %}Profile - {{ user.username }}{% endblock %}
{% load static crispy_forms_tags %}

{% block content %}
<header class="masthead" style="background-color: crimson;">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>403 :(</h1>
          <span class="subheading">You haven't access to view this page</span>
        </div>
      </div>
    </div>
  </div>
</header>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'blog/base.html' %}{% block title %}Profile - {{ user.username }}{% endblock %}
{% load static crispy_forms_tags %}

{% block content %}
<header class="masthead" style="background-image: url('{% static 'assets/img/home-bg.jpg' %}')">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>Profile</h1>
          <span class="subheading">Welcome <strong>{{ user.username|title }}</strong> dear</span>
        </div>
      </div>
    </div>
  </div>
</header>

<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="row">
      <div class="col-md-8 mb-4">
        <h1>Profile</h1>
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
          {{ message }}
        </div>
        {% endfor %}
        <form action="" method="post">{% csrf_token %}
          {{ form|crispy }}
          <button type="submit" class="btn btn-success mt-2">Save</button>
        </form>
        <hr>
        <h1 class="mt-4">My Posts</h1>
        <ul class="list-group">
          {% for post in user.posts.all %}
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <a href="{{ post.get_absolute_url }}">{{ post.title|truncatewords:7 }}</a>
            <div>
              <a type="button" post-id="{{ post.id }}" class="btn btn-outline-danger btn-sm"
                href="{% url 'blog:delete' pk=post.id slug=post.slug %}">Delete</a>
              <a type="button" post-id="{{ post.id }}" class="btn btn-outline-success btn-sm"
                href="{% url 'blog:edit' pk=post.id slug=post.slug %}">Edit</a>
            </div>
          </li>
          {% empty %}
          <li class="list-group-item">No posts <a href="{% url 'blog:add' %}" class="text text-primary">+ Add</a></li>
          {% endfor %}
        </ul>
      </div>
      <div class="col-md-4">
      <h1>Actions</h1>
        <div class="list-group mt-4">
          <a href="{% url 'blog:add' %}" class="list-group-item list-group-item-action">Add Posts</a>
          {% if not user.is_verified %}
          <a href="{% url 'api-user:verify-user' %}" class="list-group-item list-group-item-action">Verify account</a>
          {% endif %}
          <a href="{% url 'password_change' %}" class="list-group-item list-group-item-action">Chanage Password</a>
          <a href="{% url 'logout' %}" class="list-group-item list-group-item-action">Logout</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/unverified_user.html
{% extends 'blog/base.html' %}{% block title %}Profile - {{ user.username }}{% endblock %}
{% load static crispy_forms_tags %}

{% block content %}
<header class="masthead" style="background-color: crimson;">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>403 :(</h1>
          <span class="subheading">You are not verified {{ user.username }} dear</span>
        </div>
      </div>
    </div>
  </div>
</header>

<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="row">
      <div class="col-md-8 mb-4">
        <h1>Please verify your account!</h1>
        <a href="{% url 'api-user:verify-user' %}">Click here to verify your account right now :)</a>  
      </div>
      
    </div>
  </div>
</div>


{% endblock %}