accounts/urls.py
from django.urls import path

from .views import user_profile_view, SignupView

app_name = 'accounts'
urlpatterns = [
    path('profile/', user_profile_view, name='profile'),
    path('signup/', SignupView.as_view(), name='signup')
]

api/blog/urls.py
from django.urls import path

from .views import PostListAPIView, PostDetailAPIView

app_name = 'api-blog'

urlpatterns = [
    path('', PostListAPIView.as_view(), name='list'),
    path('<str:pk>/', PostDetailAPIView.as_view(), name='detail'),
]

blog/urls.py
from django.urls import path

from .views import PostListView, PostDetailView, CreatePostView, DeletePostView, UpdatePostView


app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='list'),
    path('<int:pk>/<str:slug>/', PostDetailView.as_view(), name='detail'),
    path('add/', CreatePostView.as_view(), name='add'),
    path('<int:pk>/<str:slug>/delete/', DeletePostView.as_view(), name='delete'),
    path('<int:pk>/<str:slug>/edit/', UpdatePostView.as_view(), name='edit'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import permissions 
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title='Blog API',
        default_version='v1',
        description="A sample API for learning DRF",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="hello@example.com"),
        license=openapi.License(name="BSD License"),
        ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    
    # API VERSION 1
    path('api/v1/blog/', include('api.blog.urls')),
    path('api/v1/users/', include('api.users.urls')),
    
    # AUTHENTICATION
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # Documenting
    path('swagger/', schema_view.with_ui(
        'swagger', cache_timeout=0
    ), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui(
        'redoc', cache_timeout=0
    ), name='schema-redoc'),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.text import slugify

from .messages import PostMessages


User = get_user_model()


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts', related_query_name='post')
    title = models.CharField(max_length=200)
    subheading = models.TextField(help_text=PostMessages.MARKDOWN_AVAILABLE.value)
    body = models.TextField(help_text=PostMessages.MARKDOWN_AVAILABLE.value)
    reading_time = models.DurationField(help_text=PostMessages.READING_TIME_HELP_TEXT.value) # in seconds
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-date_created', '-date_updated')

    def __str__(self) -> str:
        return self.title

    @property
    def slug(self):
        slug = slugify(self.title, allow_unicode=True)
        return slug 

    def get_absolute_url(self):
        slug = self.slug
        return reverse('blog:detail', kwargs={'pk':self.id, 'slug':slug})

api/blog/views.py
from rest_framework import generics, permissions

from blog.models import Post
from api.users.permissions import IsUserVerified

from . import permissions as custom_permission
from .serializers import PostSerializer


class PostListAPIView(generics.ListCreateAPIView):
    queryset = Post.objects.all().order_by('-date_updated')
    serializer_class = PostSerializer
    permission_classes = [permissions.IsAuthenticated, IsUserVerified]

    def perform_create(self, serializer):
        """ Overwriting this method only for setting the author instance """
        serializer.save(author=self.request.user)


class PostDetailAPIView(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = [permissions.IsAuthenticated,
                          IsUserVerified, custom_permission.IsAuthorOrReadOnly]
    queryset = Post.objects.all()
    serializer_class = PostSerializer

blog/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages

from .models import Post
from .mixins import UserVerifiedPermission, IsAuthorAndVerifiedPermission
from .messages import PostMessages 


class PostListView(LoginRequiredMixin,
                    UserVerifiedPermission, ListView):
    login_url = '/accounts/login/'
    model = Post
    template_name = 'blog/index.html'
    paginate_by = 20


class PostDetailView(LoginRequiredMixin,
                    UserVerifiedPermission, DetailView):
    login_url = '/accounts/login/'
    model = Post
    template_name = 'blog/post.html'


class CreatePostView(LoginRequiredMixin,
                    UserVerifiedPermission, CreateView):
    login_url = '/accounts/login/'
    model = Post
    fields = ('title', 'subheading', 'body', 'reading_time')
    template_name = 'blog/create_post.html'

    def form_valid(self, form):
        """ When submitting form if that valid author will set for this post """
        form.instance.author = self.request.user
        messages.add_message(self.request, messages.SUCCESS, PostMessages.POST_CREATED_SUCCESSFULLY.value)
        return super().form_valid(form)


class DeletePostView(LoginRequiredMixin,
                    IsAuthorAndVerifiedPermission,
                    DeleteView):
    login_url = '/accounts/login/' 
    model = Post
    template_name = 'blog/delete_post.html'

    def form_valid(self, form):
        """ When submitting form if that valid author will set for this post """
        messages.add_message(self.request, messages.SUCCESS, PostMessages.POST_DELETED_SUCCESSFULLY.value)
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse('accounts:profile')


class UpdatePostView(LoginRequiredMixin,
                    IsAuthorAndVerifiedPermission,
                    UpdateView):
    login_url = '/accounts/login/'
    model = Post
    fields = ('title', 'subheading', 'body', 'reading_time')
    template_name = 'blog/update_post.html'

    def form_valid(self, form):
        """ When submitting form if that valid adding message """
        messages.add_message(self.request, messages.SUCCESS, PostMessages.POST_UPDATED_SUCCESSFULLY.value)
        return super().form_valid(form)

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <title>{% block title %}{% endblock %}</title>
  <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
  <!-- Font Awesome icons (free version)-->
  <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
  <!-- Google fonts-->
  <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet"
    type="text/css" />
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
    rel="stylesheet" type="text/css" />
  <!-- Core theme CSS (includes Bootstrap)-->
  <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>

<body>
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5">
      <a class="navbar-brand" href="{% url 'blog:list' %}">Nice Blog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ms-auto py-4 py-lg-0">
          <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:list' %}">Home</a></li>
          {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'accounts:profile' %}">Profile</a></li>
          <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'accounts:signup' %}">Signup</a></li>
          <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  {% block content %}
  {% endblock %}

  <!-- Footer-->
  <footer class="border-top">
    <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#!">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#!">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#!">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
        </div>
      </div>
    </div>
  </footer>
  <!-- Bootstrap core JS-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  <!-- Core theme JS-->
  <script src="{% static 'js/scripts.js' %}"></script>
</body>

</html>

blog/templates/blog/create_post.html
{% extends 'blog/base.html' %}{% block title %}Add Post{% endblock %}
{% load static crispy_forms_tags %}

{% block content %}
<header class="masthead" style="background-image: url('{% static 'assets/img/home-bg.jpg' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Add post</h1>
                    <span class="subheading">Add your post as quick</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="row">
            <div class="col-md-8 mb-4">
                <h1>Post detail</h1>
                <form action="" method="post">{% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-success mt-2">Save</button>
                </form>
                <hr>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/delete_post.html
{% extends 'blog/base.html' %}{% block title %}Delete Post - {{ object.title }}{% endblock %}
{% load static crispy_forms_tags %}

{% block content %}
<header class="masthead" style="background-image: url('{% static 'assets/img/home-bg.jpg' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Delete post</h1>
                    <span class="subheading">Do you want to delete this post?</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="row">
            <div class="col-md-8 mb-4">
                <h1>Post Delete</h1>
                <form action="" method="post">{% csrf_token %}
                    <p>Are you sure you want to delete <a class="text text-danger text-decoration-none" href="{{ object.get_absulote_url }}">"{{ object.title }}"</a> post?</p>
                    <button type="submit" class="btn btn-danger mt-2">Yes</button>
                </form>
                <hr>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}{% block title %}Blog{% endblock %}
{% load static markdown_tools %}

{% block content %}

<!-- Page Header-->
<header class="masthead" style="background-image: url('{% static 'assets/img/home-bg.jpg' %}')">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>Nice Blog</h1>
          <span class="subheading">A nice blog with cool features</span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Main Content-->
<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      {% for post in object_list %}
      <!-- Post preview-->
      <div class="post-preview">
        <a href="{{ post.get_absolute_url }}">
          <h2 class="post-title">{{ post.title }}</h2>
          <h3 class="post-subtitle">{{ post.subheading|markdown|safe }}</h3>
        </a>
        <p class="post-meta">
          Posted by
          <a href="#!">{{ post.author.username }}</a>
          on {{ post.date_created|date:'F d, Y' }}
        </p>
      </div>
      <!-- Divider-->
      <hr class="my-4" />
      {% endfor %}
      <!-- Pager-->
      <div class="d-flex justify-content-between">

        {% if page_obj.has_previous %}
        <div class="d-flex justify-content-start mb-4">
          <a class="btn btn-primary text-uppercase" href="?page={{ page_obj.previous_page_number }}">
            <i class="fa fa-angle-left"></i> Previous Page</a>
          </a>
        </div>
        {% endif %}
        {% if page_obj.has_next %}
        <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase"
            href="?page={{ page_obj.next_page_number }}">Next Page
            <i class="fa fa-angle-right"></i></a></div>
        </a>
        {% endif %}
      </div>
    </div>

  </div>
</div>
{% endblock %}

blog/templates/blog/post.html
{% extends 'blog/base.html' %}{% block title %}{{ object.title }} - {{ object.author.username }}{% endblock %}
{% load static markdown_tools %}

{% block content %}
<!-- Page Header-->
<header class="masthead" style="background-image: url({% static 'assets/img/post-bg.jpg' %})">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="post-heading">
          <h1>{{ object.title }}</h1>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Post Content-->
<article class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="header">
          <p class="subheading">
            <h3>Details</h3>
            Posted by <a href="">{{ object.author.username }}</a>
            on <strong>{{ post.date_created|date:'F d, Y' }}</strong>
            <br>
            Updated on <strong> {{ post.date_updated|date:'F d, Y' }}</strong>
            <br>
            Reading time: <strong>{{ object.reading_time }}</strong>
          </p>
          <hr>
        </div>
        <div>
          <h3>Subheader</h3>
          {{ object.subheading|markdown|safe }}
          <hr>
        </div>
        <div>
          <h3>Content</h3>
          {{ object.body|markdown|safe }}
        </div>
      </div>
    </div>
  </div>
</article>
{% endblock %}

blog/templates/blog/update_post.html
{% extends 'blog/base.html' %}{% block title %}Edit Post - {{ object.title }}{% endblock %}
{% load static crispy_forms_tags %}

{% block content %}
<header class="masthead" style="background-image: url('{% static 'assets/img/home-bg.jpg' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Edit post</h1>
                    <span class="subheading">Edit your post as quick</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="row">
            <div class="col-md-8 mb-4">
                <h1>Post detail</h1>
                <form action="" method="post">{% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-success mt-2">Save</button>
                </form>
                <hr>
            </div>
        </div>
    </div>
</div>
{% endblock %}